# Generated by Django 6.1.1 on 2026-09-23 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idols', '0011_idolprofile_banner_idolprofile_specialties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(unique=True, verbose_name='ID de Telegram')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario de Telegram')),
                ('title', models.CharField(choices=[('plebeyo', 'Curioso Clandestino 🍷'), ('caballero', 'Caballero VIP 🥂'), ('conde', 'Conde de la Fortuna 🪙'), ('duque', 'Duque Imperial 👑'), ('archiduque', 'Archiduque del Placer 💎')], default='caballero', max_length=50, verbose_name='Título Nobiliario')),
                ('bio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Biografía / Presentación')),
                ('avatar_frame', models.CharField(choices=[('gold', 'Borde Oro Pulido 👑'), ('neon', 'Borde Neón Púrpura 🟣'), ('diamond', 'Borde Diamante Glacial 💎'), ('flame', 'Borde Llama Carmesí 🔥')], default='gold', max_length=20, verbose_name='Marco de Avatar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorite_idol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoted_nobles', to='idols.idolprofile', verbose_name='Musa / Idol Favorita')),
            ],
        ),
    ]
