# Generated by Django 6.1.1 on 2026-09-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='motto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lema o Frase Insignia'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_theme',
            field=models.CharField(choices=[('velvet', 'Terciopelo Imperial'), ('obsidian', 'Obsidiana & Neón'), ('crimson', 'Carmesí Clandestino'), ('champagne', 'Champagne Real')], default='velvet', max_length=30, verbose_name='Tema de Fondo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vip_badge',
            field=models.CharField(choices=[('none', 'Sin Insignia'), ('high_roller', '🎰 High Roller Casino'), ('mecenas', '💎 Mecenas Imperial'), ('romantico', '🌹 Caballero Devoto'), ('coleccionista', '🐾 Domador de Bestias')], default='none', max_length=30, verbose_name='Insignia Nobiliaria'),
        ),
    ]
