# Generated by Django 6.1.1 on 2026-09-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_motto_userprofile_profile_theme_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_tg_id', models.BigIntegerField()),
                ('action', models.CharField(max_length=50)),
                ('target_tg_id', models.BigIntegerField(blank=True, null=True)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KingdomSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrador Supremo 👑'), ('moderador', 'Moderador Imperial 🛡️'), ('idol', 'Musa / Creadora VIP 🌹'), ('vip', 'Noble VIP 🥂'), ('cliente', 'Súbdito Ordinario 🍷')], default='cliente', max_length=20)),
                ('is_banned', models.BooleanField(default=False)),
                ('ban_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
