# Generated by Django 6.1.1 on 2026-09-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adminauditlog_kingdomsetting_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='ban_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo de Suspensión'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='¿Baneado?'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='ID de Telegram'),
        ),
    ]
