# Generated by Django 6.1.1 on 2026-09-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userrole_ban_reason_alter_userrole_is_banned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_xp',
            field=models.PositiveIntegerField(default=0, verbose_name='EXP Acumulada en Nivel Actual'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='Nivel Nobiliario'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_xp',
            field=models.PositiveIntegerField(default=0, verbose_name='EXP Histórica Total'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(choices=[('plebeyo', 'Curioso Clandestino 🍷'), ('caballero', 'Caballero VIP 🥂'), ('conde', 'Conde de la Fortuna 🪙'), ('duque', 'Duque Imperial 👑'), ('archiduque', 'Archiduque del Placer 💎')], default='plebeyo', max_length=50, verbose_name='Título Nobiliario'),
        ),
    ]
