# Generated by Django 6.1.1 on 2026-10-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_current_xp_userprofile_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Biografía / Presentación'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_xp',
            field=models.PositiveIntegerField(default=0, verbose_name='EXP en Nivel Actual'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='motto',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Lema o Frase Insignia'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='title',
            field=models.CharField(choices=[('plebeyo', 'Curioso Clandestino 🍷'), ('iniciado', 'Iniciado del Placer ✨'), ('caballero', 'Caballero VIP 🥂'), ('baron', 'Barón de la Fortuna 🪙'), ('conde', 'Conde Estelar 💎'), ('marques', 'Marqués del Deseo 🌹'), ('duque', 'Duque Imperial 👑'), ('soberano', 'Soberano Absoluto ⚜️')], default='plebeyo', max_length=50, verbose_name='Título Nobiliario'),
        ),
    ]
