# Generated by Django 6.1.1 on 2026-10-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userprofile_bio_alter_userprofile_current_xp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_title_text',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Título Personalizado de Rol'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_custom_avatar_frame',
            field=models.BooleanField(default=False, verbose_name='Acceso a Marcos Imperiales'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_vip_badge',
            field=models.BooleanField(default=False, verbose_name='Insignia de Linaje VIP'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inactivity_shield_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inmunidad por Inactividad hasta'),
        ),
    ]
