# Generated by Django 6.1.1 on 2026-09-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='ID del Dueño')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la Mascota')),
                ('species', models.CharField(choices=[('panther', 'Pantera de Ébano'), ('fox', 'Zorro Kitsune Dorado'), ('viper', 'Víbora de Esmeralda')], max_length=20, verbose_name='Especie')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Nivel')),
                ('xp', models.PositiveIntegerField(default=0, verbose_name='Experiencia')),
                ('energy', models.PositiveIntegerField(default=80, verbose_name='Energía / Saciedad')),
                ('last_fed', models.DateTimeField(auto_now_add=True, verbose_name='Última vez alimentada')),
                ('last_petted', models.DateTimeField(auto_now_add=True, verbose_name='Última caricia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
