# Generated by Django 6.1.1 on 2026-09-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='last_fed',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='last_petted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('panther', 'Pantera de Ébano'), ('fox', 'Zorro Kitsune Dorado'), ('viper', 'Víbora de Esmeralda'), ('raven', 'Cuervo de Medianoche'), ('wolf', 'Lobo Espectral de Plata')], max_length=20, verbose_name='Especie'),
        ),
    ]
