# Generated by Django 6.1.1 on 2026-10-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_last_fed_alter_pet_last_petted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='happiness',
            field=models.PositiveIntegerField(default=75, verbose_name='Felicidad / Vínculo'),
        ),
        migrations.AddField(
            model_name='pet',
            name='last_expedition',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Expedición'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('panther', 'Pantera de Ébano 🐆'), ('fox', 'Zorro Kitsune Dorado 🦊'), ('viper', 'Víbora de Esmeralda 🐍'), ('raven', 'Cuervo de Medianoche 🦅'), ('wolf', 'Lobo Espectral de Plata 🐺')], max_length=20, verbose_name='Especie'),
        ),
    ]
