# Generated by Django 6.1.1 on 2026-10-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_happiness_pet_last_expedition_alter_pet_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='happiness',
            field=models.PositiveIntegerField(default=70, verbose_name='Felicidad / Vínculo'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='last_expedition',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='last_fed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='last_petted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
