# Generated by Django 6.1.1 on 2026-10-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_happiness_alter_pet_last_expedition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(default='fox', max_length=50, verbose_name='Especie Base'),
        ),
    ]
