# Generated by Django 6.1.1 on 2026-10-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_pet_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('panther', 'Pantera de Ébano 🐆'), ('fox', 'Zorro Kitsune Dorado 🦊'), ('viper', 'Víbora de Esmeralda 🐍'), ('raven', 'Cuervo de Medianoche 🦅'), ('wolf', 'Lobo Espectral de Plata 🐺'), ('dragon', 'Dragón Carmesí 🐉'), ('owl', 'Búho Cronos 🦉'), ('deer', 'Ciervo de Jade 🦌'), ('scorpion', 'Escorpión Dorado 🦂'), ('rabbit', 'Conejo Lunar 🐇')], default='fox', max_length=50, verbose_name='Especie Base'),
        ),
    ]
