# Generated by Django 6.1.1 on 2026-09-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(db_index=True)),
                ('stage_name', models.CharField(max_length=100, verbose_name='Nombre Artístico')),
                ('group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo/Solista')),
                ('bio', models.TextField(max_length=500, verbose_name='Biografía / Presentación')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='URL de la Foto')),
                ('services_done', models.IntegerField(default=0, verbose_name='Servicios Realizados')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Calificación Promedio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil de Idol',
                'verbose_name_plural': 'Perfiles de Idols',
                'ordering': ['-created_at'],
            },
        ),
    ]
