# Generated by Django 6.1.1 on 2026-09-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idolprofile',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='idolprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='idols_photos/', verbose_name='Foto de Perfil'),
        ),
    ]
