# Generated by Django 6.1.1 on 2026-09-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0002_remove_idolprofile_photo_url_idolprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='idolprofile',
            name='owner_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario de Telegram'),
        ),
    ]
