# Generated by Django 6.1.1 on 2026-09-09 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0003_idolprofile_owner_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_telegram_id', models.BigIntegerField(db_index=True, verbose_name='ID del Cliente')),
                ('client_username', models.CharField(max_length=100, verbose_name='Cliente')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Calificación (1 a 5)')),
                ('comment', models.TextField(max_length=300, verbose_name='Comentario / Reseña')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='idols.idolprofile')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-created_at'],
            },
        ),
    ]
