# Generated by Django 6.1.1 on 2026-09-09 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('gram', 'KingdomGram (Público)'), ('fans', 'KingdomFans (VIP / Pago)')], default='gram', max_length=10, verbose_name='Red Social')),
                ('image', models.ImageField(upload_to='social_posts/', verbose_name='Foto del Post')),
                ('caption', models.TextField(max_length=300, verbose_name='Descripción')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Precio en Oro (0 si es Público)')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Me Gusta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='idols.idolprofile')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_telegram_id', models.BigIntegerField(db_index=True, verbose_name='ID del Cliente')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='idols.post')),
            ],
            options={
                'unique_together': {('post', 'client_telegram_id')},
            },
        ),
    ]
