# Generated by Django 6.1.1 on 2026-09-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0005_post_postunlock'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('idol', 'Idol'), ('cliente', 'Cliente')], max_length=10)),
            ],
        ),
    ]
