# Generated by Django 6.1.1 on 2026-09-16 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0006_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_telegram_id', models.BigIntegerField(db_index=True, verbose_name='ID del Usuario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='idols.post')),
            ],
            options={
                'unique_together': {('post', 'client_telegram_id')},
            },
        ),
    ]
