# Generated by Django 6.1.1 on 2026-09-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0007_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='idolprofile',
            name='status',
            field=models.CharField(choices=[('online', '🟢 Chateando en Telegram'), ('antojos', '🔥 Sesión de Antojos'), ('offline', '🌙 Descansando')], default='online', max_length=10, verbose_name='Estado Actual'),
        ),
    ]
