# Generated by Django 6.1.1 on 2026-09-17 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0008_idolprofile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_telegram_id', models.BigIntegerField(db_index=True, verbose_name='ID del Cliente')),
                ('client_username', models.CharField(max_length=100, verbose_name='Cliente')),
                ('description', models.TextField(max_length=300, verbose_name='Detalle del Antojo')),
                ('bounty', models.PositiveIntegerField(default=100, verbose_name='Oro Ofrecido')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Entregada'), ('rejected', 'Rechazada')], default='pending', max_length=10, verbose_name='Estado')),
                ('delivered_photo', models.ImageField(blank=True, null=True, upload_to='custom_antojos/', verbose_name='Foto Entregada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_requests', to='idols.idolprofile')),
            ],
            options={
                'verbose_name': 'Petición de Antojo',
                'verbose_name_plural': 'Peticiones de Antojos',
                'ordering': ['-created_at'],
            },
        ),
    ]
