# Generated by Django 6.1.1 on 2026-09-17 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0009_customrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_telegram_id', models.BigIntegerField(db_index=True, verbose_name='ID del Autor')),
                ('author_name', models.CharField(max_length=100, verbose_name='Nombre o @ de Usuario')),
                ('text', models.TextField(max_length=250, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='idols.post')),
            ],
            options={
                'verbose_name': 'Comentario de Post',
                'verbose_name_plural': 'Comentarios de Posts',
                'ordering': ['created_at'],
            },
        ),
    ]
