# Generated by Django 6.1.1 on 2026-09-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0010_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='idolprofile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='idols_banners/', verbose_name='Foto de Portada'),
        ),
        migrations.AddField(
            model_name='idolprofile',
            name='specialties',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Especialidades (separadas por comas)'),
        ),
        migrations.AddField(
            model_name='idolprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Lema / Frase Seductora'),
        ),
        migrations.AddField(
            model_name='idolprofile',
            name='theme_color',
            field=models.CharField(choices=[('gold', 'Oro Imperial 👑'), ('purple', 'Púrpura Clandestino 🟣'), ('crimson', 'Carmesí Pasión 🌹')], default='gold', max_length=20, verbose_name='Aura Visual'),
        ),
    ]
