# Generated by Django 6.1.1 on 2026-09-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0011_idolprofile_banner_idolprofile_specialties_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idolprofile',
            name='specialties',
        ),
        migrations.RemoveField(
            model_name='idolprofile',
            name='theme_color',
        ),
        migrations.AddField(
            model_name='idolprofile',
            name='aura_color',
            field=models.CharField(choices=[('purple', 'Aura Mística Púrpura 💜'), ('gold', 'Aura Celestial Dorada 💛'), ('ruby', 'Aura Pasión Rubí ❤️'), ('emerald', 'Aura Seducción Esmeralda 💚')], default='purple', max_length=30, verbose_name='Aura de la Idol'),
        ),
        migrations.AddField(
            model_name='idolprofile',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='idolprofile',
            name='welcome_message',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Saludo de Bienvenida'),
        ),
        migrations.AlterField(
            model_name='idolprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Subtítulo / Esencia'),
        ),
    ]
