# Generated by Django 6.1.1 on 2026-10-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0012_remove_idolprofile_specialties_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
