# Generated by Django 6.1.1 on 2026-10-05 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0013_delete_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotocardBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Caja')),
                ('description', models.TextField(max_length=300, verbose_name='Descripción / Temática')),
                ('price', models.PositiveIntegerField(default=50, verbose_name='Costo de Apertura (🪙)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='photocard_boxes/', verbose_name='Portada de la Caja')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activa para abrir?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Caja de Photocards',
                'verbose_name_plural': 'Cajas de Photocards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photocard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Carta')),
                ('rarity', models.CharField(choices=[('common', 'Común ⚪'), ('rare', 'Rara 🔵'), ('epic', 'Épica 🟣'), ('legendary', 'Legendaria 👑')], default='common', max_length=20, verbose_name='Rareza')),
                ('image', models.ImageField(upload_to='photocards/', verbose_name='Imagen Photocard (Canva)')),
                ('created_by_tg_id', models.BigIntegerField(verbose_name='ID del Admin Creador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photocards', to='idols.idolprofile', verbose_name='Musa / Idol')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='idols.photocardbox', verbose_name='Caja a la que pertenece')),
            ],
            options={
                'verbose_name': 'Photocard',
                'verbose_name_plural': 'Photocards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPhotocard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(db_index=True, verbose_name='ID del Dueño (Idol o Noble)')),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('photocard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='idols.photocard')),
            ],
            options={
                'verbose_name': 'Photocard de Usuario',
                'verbose_name_plural': 'Photocards de Usuarios',
                'ordering': ['-obtained_at'],
            },
        ),
    ]
