# Generated by Django 6.1.1 on 2026-10-05 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0014_photocardbox_photocard_userphotocard'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocard',
            name='idol_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Idol de K-Pop / Artista'),
        ),
        migrations.AlterField(
            model_name='photocard',
            name='idol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photocards', to='idols.idolprofile', verbose_name='Musa del Rol (Opcional)'),
        ),
    ]
