# Generated by Django 6.1.1 on 2026-10-05 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0015_photocard_idol_name_alter_photocard_idol'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphotocard',
            name='is_for_sale',
            field=models.BooleanField(default=False, verbose_name='¿Puesta a la venta?'),
        ),
        migrations.AddField(
            model_name='userphotocard',
            name='sale_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Precio de Venta (🪙)'),
        ),
        migrations.CreateModel(
            name='PhotocardTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_telegram_id', models.BigIntegerField(db_index=True, verbose_name='Emisor')),
                ('sender_username', models.CharField(default='Noble', max_length=100, verbose_name='Usuario Emisor')),
                ('receiver_telegram_id', models.BigIntegerField(db_index=True, verbose_name='Receptor')),
                ('receiver_username', models.CharField(default='Noble', max_length=100, verbose_name='Usuario Receptor')),
                ('status', models.CharField(choices=[('pending', 'Pendiente ⏳'), ('accepted', 'Aceptado ✅'), ('rejected', 'Rechazado ❌'), ('cancelled', 'Cancelado 🚫')], default='pending', max_length=15, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades_received', to='idols.userphotocard')),
                ('sender_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_sent', to='idols.userphotocard')),
            ],
            options={
                'verbose_name': 'Intercambio de Photocard',
                'verbose_name_plural': 'Intercambios de Photocards',
                'ordering': ['-created_at'],
            },
        ),
    ]
