# Generated by Django 6.1.1 on 2026-10-06 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0016_userphotocard_is_for_sale_userphotocard_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idolprofile',
            name='is_featured_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Destacada en Galería hasta'),
        ),
        migrations.AlterField(
            model_name='photocard',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='idols.photocardbox', verbose_name='Caja a la que pertenece'),
        ),
        migrations.CreateModel(
            name='IdolTribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_telegram_id', models.BigIntegerField(db_index=True, verbose_name='ID del Noble Emisor')),
                ('client_username', models.CharField(max_length=100, verbose_name='Noble Emisor')),
                ('gift_name', models.CharField(max_length=100, verbose_name='Obsequio de Corte')),
                ('gold_value', models.PositiveIntegerField(default=150, verbose_name='Valor en Oro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tributes', to='idols.idolprofile', verbose_name='Musa Agasajada')),
            ],
            options={
                'verbose_name': 'Tributo de Musa',
                'verbose_name_plural': 'Tributos de Musas',
                'ordering': ['-created_at'],
            },
        ),
    ]
