# Generated by Django 6.1.1 on 2026-10-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0017_idolprofile_is_featured_until_alter_photocard_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='social_videos/', verbose_name='Video del Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='social_posts/', verbose_name='Foto del Post'),
        ),
    ]
