# Generated by Django 6.1.1 on 2026-09-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='last_bonus_claim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último bono'),
        ),
    ]
