# Generated by Django 6.1.1 on 2026-09-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_wallet_last_bonus_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(default=150, verbose_name='Monedas de Oro'),
        ),
    ]
