# Generated by Django 6.1.1 on 2026-10-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0003_alter_wallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(db_index=True, verbose_name='ID del Usuario')),
                ('item_code', models.CharField(db_index=True, max_length=50, verbose_name='Código de Ítem')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ítem de Inventario',
                'verbose_name_plural': 'Ítems de Inventario',
                'unique_together': {('telegram_user_id', 'item_code')},
            },
        ),
    ]
