"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url  # 👈 AÑADIR ESTE IMPORT

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b_gxt!(b-)8=@2gj^1@2hs7bfy!ck@=d7&@_$+x!i*)hs)m4yy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com',
    'https://*.trycloudflare.com',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',                   # 👈 Supabase / S3 Storage
    
    # Nuestras Apps
    'core',
    'idols',
    'economy',
    'pets',
    'corsheaders',
]

# En config/settings.py

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
]

# Carga WhiteNoise solo si está instalado (en Render); si no, no bloquea las pruebas locales
try:
    import whitenoise
    MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')
except ImportError:
    pass

MIDDLEWARE += [
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'core.middleware.TelegramSessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.kingdom_notifications', # 👈 AÑADIR ESTA LÍNEA
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# ✅ REEMPLAZAR POR:
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/Santiago' # Ajustado a horario de Chile

USE_I18N = True
USE_TZ = True

# Añadir al final del archivo (permite que Telegram lea nuestro backend en desarrollo)
CORS_ALLOW_ALL_ORIGINS = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 👈 AÑADIR ESTA LÍNEA (compatibilidad Django 6 con Cloudinary y WhiteNoise):
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Archivos subidos por los usuarios
MEDIA_URL = '/media/' 
MEDIA_ROOT = BASE_DIR / 'media'

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# Configuraciones de Telegram
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '8966798192:AAHTaCsfbW9Mlzrkoa8PiZJT-DrlryD4dP8')

# ID de tu grupo privado de rol en Telegram
TELEGRAM_GROUP_ID = int(os.environ.get('TELEGRAM_GROUP_ID', -1004393120413))

TELEGRAM_INTERVIEW_GROUP_URL = os.environ.get(
    'TELEGRAM_INTERVIEW_GROUP_URL', 
    'https://t.me/KingdomOfPleasureOf')

# Permitir que Telegram WebApp cargue el sitio en su iframe
X_FRAME_OPTIONS = 'ALLOWALL'

# Permitir que la sesión sobreviva dentro del iframe de Telegram
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True

# ==========================================
# ALMACENAMIENTO MULTIMEDIA (SUPABASE S3 / LOCAL)
# ==========================================
SUPABASE_ACCESS_KEY = os.environ.get('SUPABASE_ACCESS_KEY')
SUPABASE_SECRET_KEY = os.environ.get('SUPABASE_SECRET_KEY')
SUPABASE_STORAGE_URL = os.environ.get('SUPABASE_STORAGE_URL')
SUPABASE_BUCKET_NAME = os.environ.get('SUPABASE_BUCKET_NAME', 'kingdom-media')

if SUPABASE_ACCESS_KEY and SUPABASE_SECRET_KEY:
    # 🌟 PRODUCCIÓN: Guardar fotos y videos en Supabase Storage
    AWS_ACCESS_KEY_ID = SUPABASE_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY = SUPABASE_SECRET_KEY
    AWS_STORAGE_BUCKET_NAME = SUPABASE_BUCKET_NAME
    AWS_S3_ENDPOINT_URL = SUPABASE_STORAGE_URL
    AWS_S3_REGION_NAME = 'us-east-1'
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False

    # 👈 ESTA ES LA CLAVE: Construye la URL pública directa de Supabase CDN
    # Tu Project ID de Supabase es 'btoemzqyzacbjfvjwpgv'
    AWS_S3_CUSTOM_DOMAIN = f"btoemzqyzacbjfvjwpgv.supabase.co/storage/v1/object/public/{SUPABASE_BUCKET_NAME}"

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    # 💻 LOCAL: Guardar en disco duro de desarrollo
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }